zeroFruit/el

core/src/main/java/io/el/internal/DefaultPriorityQueue.java, core/src/main/java/io/el/internal/PriorityQueue.java, core/src/main/java/io/el/internal/PriorityQueueNode.java, core/src/test/java/io/el/internal/DefaultPriorityQueueTest.java
=> Add PriorityQueue

core/src/main/java/io/el/concurrent/AbstractEventLoop.java, core/src/main/java/io/el/concurrent/EventLoop.java, core/src/main/java/io/el/concurrent/SingleThreadEventLoop.java, core/src/main/java/io/el/concurrent/ThreadPerTaskExecutor.java, core/src/test/java/io/el/concurrent/SingleThreadEventLoopTest.java
implement serialized version of single thread event loop
#5
=> impl serialize single thread event loop

core/src/main/java/io/el/concurrent/DefaultTask.java, core/src/main/java/io/el/concurrent/EventLoop.java, core/src/main/java/io/el/concurrent/SingleThreadEventLoop.java, core/src/main/java/io/el/internal/DefaultPriorityQueue.java, core/src/test/java/io/el/concurrent/SingleThreadEventLoopTest.java
=> update shutdownGracefully with tests

core/build.gradle, core/src/main/java/io/el/concurrent/DefaultTask.java, core/src/main/java/io/el/concurrent/ScheduledTask.java, core/src/main/java/io/el/concurrent/SingleThreadEventLoop.java, core/src/main/java/io/el/internal/DefaultPriorityQueue.java, core/src/main/java/io/el/internal/Time.java, core/src/test/java/io/el/concurrent/SingleThreadEventLoopTest.java
=> feat: add logger and print out message with logger

core/src/main/java/io/el/concurrent/DefaultTask.java, core/src/main/java/io/el/concurrent/ScheduledTask.java, core/src/test/java/io/el/concurrent/DefaultTaskTest.java, core/src/test/java/io/el/concurrent/SingleThreadEventLoopTest.java, core/src/test/java/io/el/internal/DefaultPriorityQueueTest.java
=> fix: rm cancel() from Task

core/src/main/java/io/el/concurrent/EventLoop.java, core/src/main/java/io/el/concurrent/SingleThreadEventLoop.java, example/build.gradle, example/src/main/java/io/el/example/tasks/SimpleTask.java, example/src/main/java/io/el/example/tasks/TaskExecuteScheduler.java, example/src/main/resources/log4j2.yaml, settings.gradle
=> add example code for core package

core/src/main/java/io/el/concurrent/EventLoopChooserFactory.java, core/src/main/java/io/el/concurrent/EventLoopGroup.java, settings.gradle, transport/build.gradle, transport/src/main/java/io/el/channel/Channel.java, transport/src/main/java/io/el/channel/ChannelEventLoop.java, transport/src/main/java/io/el/channel/ChannelEventLoopGroup.java, transport/src/main/java/io/el/channel/ChannelHandler.java, transport/src/main/java/io/el/channel/ChannelHandlerContext.java, transport/src/main/java/io/el/channel/ChannelInboundHandler.java, transport/src/main/java/io/el/channel/ChannelInboundInvoker.java, transport/src/main/java/io/el/channel/ChannelOutboundHandler.java, transport/src/main/java/io/el/channel/ChannelOutboundInvoker.java, transport/src/main/java/io/el/channel/ChannelPipeline.java, transport/src/main/java/io/el/channel/ChannelPromise.java
PR added transport module and added basic component interface. It resolves #29
=> add transport module and define basic component interface

transport/build.gradle, transport/src/main/java/io/el/channel/AbstractChannelHandlerContext.java, transport/src/main/java/io/el/channel/ChannelHandlerContext.java, transport/src/main/java/io/el/channel/ChannelHandlerFlag.java, transport/src/main/java/io/el/channel/ChannelInboundHandler.java, transport/src/main/java/io/el/channel/ChannelInboundInvoker.java, transport/src/test/java/io/el/channel/AbstractChannelHandlerContextTests.java
TODO
- left to add comments
- resolved #31
=> Implement AbstractChannelHandlerContext

core/src/main/java/io/el/concurrent/Promise.java, transport/src/main/java/io/el/channel/ChannelPromise.java, transport/src/main/java/io/el/channel/DefaultChannelPromise.java
it resolves #39 
Implement DefaultChannelPromise and add java doc to Promise interface
=> implement DefaultChannelPromise

transport/build.gradle, transport/src/main/java/io/el/channel/ChannelHandlerContext.java, transport/src/main/java/io/el/channel/DefaultChannelPipeline.java, transport/src/test/java/io/el/channel/DefaultChannelPipelineTest.java
=> implement linked list code of DefaultChannelPipeline

.gitignore, transport/src/main/java/io/el/channel/AbstractChannel.java, transport/src/main/java/io/el/channel/Channel.java, transport/src/main/java/io/el/channel/ChannelId.java
close #44 
- Add `AbstractChannel` class skeleton
-
=> feat: add AbstractChannel skel

.github/workflows/ci.yaml, README.md
close #28 
Add GitHub Action ci workflow which checks whether it successfully builds and pass all unit tests
=> ci: add github action workflows

core/src/main/java/io/el/concurrent/SingleThreadEventLoop.java, transport/src/main/java/io/el/channel/ChannelEventLoopGroup.java, transport/src/main/java/io/el/channel/ChannelSingleThreadEventLoop.java
=> feat: implements ChannelSingleThreadEventLoop

transport/src/main/java/io/el/channel/DefaultChannelEventLoop.java
=> feat: implement ChannelSingleThreadEventLoop on DefaultChannelEventLoop

transport/src/main/java/io/el/channel/AbstractChannel.java, transport/src/main/java/io/el/channel/AbstractChannelHandlerContext.java, transport/src/main/java/io/el/channel/DefaultChannelPipeline.java, transport/src/test/java/io/el/channel/DefaultChannelPipelineTest.java
=> implement bind in DefaultChannelPipeline and AbstractChannelHandlerContext

transport/src/main/java/io/el/channel/DefaultChannelPipeline.java
=> chore: use DefaultChannelHandlerContext instead of DefaultChannelHandlerContext__

transport/src/main/java/io/el/channel/AbstractChannel.java, transport/src/main/java/io/el/channel/AbstractChannelHandlerContext.java, transport/src/main/java/io/el/channel/Channel.java, transport/src/main/java/io/el/channel/ChannelHandlerFlag.java, transport/src/main/java/io/el/channel/DefaultChannelEventLoopGroup.java, transport/src/main/java/io/el/channel/DefaultChannelPipeline.java, transport/src/test/java/io/el/channel/AbstractChannelTests.java, transport/src/test/java/io/el/channel/DefaultChannelPipelineTest.java
close #45 
This PR implements the AbstractChannel register method. And waiting for DefaultChannelPipeline to be merged. Because we need that component for testing AbstractChannel properly.
=> feat: impl AbstractChannel register

transport/src/main/java/io/el/channel/DefaultEventLoopChooserFactory.java
=> feat: implements EventLoopChooserFactory

transport/src/main/java/io/el/channel/DefaultChannelPipeline.java, transport/src/test/java/io/el/channel/AbstractChannelTests.java
=> feat: implement AstractChannelHanlerContext::fireExceptionCaught

transport/src/main/java/io/el/channel/AbstractChannel.java, transport/src/main/java/io/el/channel/AbstractChannelHandlerContext.java, transport/src/main/java/io/el/channel/Channel.java, transport/src/main/java/io/el/channel/ChannelOutboundHandler.java, transport/src/main/java/io/el/channel/ChannelOutboundInvoker.java, transport/src/main/java/io/el/channel/DefaultChannelPipeline.java, transport/src/test/java/io/el/channel/AbstractChannelHandlerContextTests.java, transport/src/test/java/io/el/channel/AbstractChannelTests.java
=> feat: implement connect

core/src/main/java/io/el/concurrent/AbstractEventLoopGroup.java, core/src/main/java/io/el/concurrent/DefaultEventLoopChooserFactory.java, core/src/main/java/io/el/internal/ObjectUtil.java, transport/src/main/java/io/el/channel/AbstractChannel.java, transport/src/main/java/io/el/channel/AbstractServerChannel.java, transport/src/main/java/io/el/channel/ChannelId.java, transport/src/main/java/io/el/channel/DefaultChannelEventLoop.java, transport/src/main/java/io/el/channel/DefaultChannelEventLoopGroup.java, transport/src/main/java/io/el/channel/local/LocalAddress.java, transport/src/main/java/io/el/channel/local/LocalChannel.java, transport/src/main/java/io/el/channel/local/LocalServerChannel.java, transport/src/test/java/io/el/channel/AbstractChannelTests.java, transport/src/test/java/io/el/channel/local/LocalChannelTests.java
close: #75 close: #59 close: #58
=> feat: add LocalChannel skel, register() method

transport/src/main/java/io/el/channel/AbstractChannel.java, transport/src/main/java/io/el/channel/AbstractChannelHandlerContext.java, transport/src/main/java/io/el/channel/DefaultChannelPipeline.java, transport/src/main/java/io/el/channel/local/LocalChannel.java, transport/src/main/java/io/el/channel/local/LocalServerChannel.java, transport/src/test/java/io/el/channel/AbstractChannelTests.java
=> feat: implement AbstractChannel bind method

transport/src/main/java/io/el/channel/AbstractChannel.java, transport/src/main/java/io/el/channel/local/LocalChannel.java, transport/src/main/java/io/el/channel/local/LocalChannelRegistry.java, transport/src/main/java/io/el/channel/local/LocalServerChannel.java, transport/src/test/java/io/el/channel/AbstractChannelTests.java
=> feat: implements LocalChannelRegistry

transport/src/main/java/io/el/channel/local/LocalChannel.java, transport/src/main/java/io/el/channel/local/LocalServerChannel.java
=> feat: implement doBind() in LocalChannel

transport/src/main/java/io/el/channel/local/LocalChannel.java, transport/src/main/java/io/el/channel/local/LocalChannelRegistry.java, transport/src/main/java/io/el/channel/local/LocalServerChannel.java
=> feat: implement connect in LocalChannel

README.md, docs/README.md, docs/event-loop.md, docs/promise.md
=> docs: update README, separate docs
